document.write('<button id=\'transition-toggle\' class="moveToVideoJs video-control hero__headline__name moveToVideoJs">');
document.write('<span class="video-control-play">');
document.write('<span class="video-control-symbol"><a href="#" class="tooltip"><span><h3>Annonce<span style="color: #ff0000;">Bande</span></h3>');
document.write('');
document.write('<p><strong>&nbsp;</strong></p></span><img src="https://www.zupimages.net/up/23/02/gu1h.png" width="53" height="49" />');
document.write('</span></a>');
document.write('</span>');
document.write('<span class="video-control-pause">');
document.write('<span id=\'transition-toggle\' class="video-control-symbol" aria-hidden="true"><a href="#" class="tooltip"><span><h3><span style="color: #ff0000;">CLOSE</span></h3>');
document.write('<p><strong>&nbsp;</strong></p></span><img src="https://www.zupimages.net/up/22/49/jneg.png" width="33" height="29" /></span>');
document.write('</span></a>');
document.write('</button>');